-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. G24F 2 23260B001788",
  mode = "1920x1080@165.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. GS27QA 0x01010101",
  mode = "2560x1440@180.00",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
