#!/usr/bin/env bash

sudo apt update
sudo apt install llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git

if [ ! -d "$HOME/.local/zig-linux-x86_64-0.13.0" ]; then
  wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
  tar -xvf /tmp/zig.tar.xz -C "$HOME"/.local
fi


if [ -d "$HOME/Downloads/ghostty" ]; then
  cd "$HOME"/Downloads/ghostty || exit
else
  git clone git@github.com:ghostty-org/ghostty.git "$HOME"/Downloads/ghostty
  cd "$HOME"/Downloads/ghostty || exit
fi

sudo env "PATH=$HOME/.local/zig-linux-x86_64-0.13.0:$PATH" zig build -p /usr/ -Doptimize=ReleaseFast
