#!/usr/bin/env bash

# lua
sudo apt install build-essential libreadline-dev unzip
curl -LO http://www.lua.org/ftp/lua-5.3.5.tar.gz
tar -xzf lua-5.3.5.tar.gz
cd lua-5.3.5 || exit
make linux test
sudo make install

# luarocks
curl -LO https://luarocks.org/releases/luarocks-3.11.0.tar.gz
tar -zxpf luarocks-3.11.0.tar.gz
cd luarocks-3.11.0 || exit
./configure && make && sudo make install
