#!/usr/bin/env bash


install_sway() {
  # sway
  sudo apt install sway sway-notification-center swayidle waybar brightnessctl swaylock clipman bemenu wlogout
}

install_i3() {
  # i3
  sudo apt install i3 i3status xclip
}

choice=4
echo "1. Install sway"
echo "2. Install i3"
echo "3. Install both"
echo -n "Chose one [1, 2, 3]: "

while [ "$choice" -eq 4 ]; do
  read -r choice
  if [ "$choice" -eq 1 ] ; then
    install_sway
  elif [ "$choice" -eq 2 ] ; then
    install_i3
  elif [ "$choice" -eq 3 ]; then
    install_sway
    install_i3
  else
    choice=4
    echo "Error! Choose [1, 2 or 3]"
    echo -n "Chose one [1, 2, 3]: "
  fi
done
