- name: Clone fzf repository
  become: true
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
  tags:
    - install
    - fzf

- name: install fzf
  become: true
  shell: cd ~/.fzf && git pull && ./install
  tags:
    - install
    - fzf
