- name: My first playbook
  tasks:
    - name: Git neovim
      ansible.builtin.git:
        repo: "https://github.com/neovim/neovim.git"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
        version: v0.9.4

    - name: Install helping libs
      become: true
      ansible.builtin.apt:
        pkg:
          - lua5.1
          - liblua5.1-0-dev
          - cmake
          - gettext

    - name: neovim
      make:
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
        params:
          CMAKE_BUILD_TYPE: "RelWithDebInfo"

    - name: neovim install
      become: true
      make:
        target: install
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
