- name: Installing tool packages
  become: true
  apt:
    name:
      [
        "tmux",
        "gimp",
        "xclip",
        "ripgrep",
        "i3",
        "i3status",
        "sway",
        "sway-notification-center",
        "swayidle",
        "fonts-recommended",
        "waybar",
        "shellcheck",
        "syncthing",
        "brightnessctl",
        "grim",
        "slurp",
        "swaylock",
        "clipman",
        "bemenu",
        "python3-neovim",
        "zsh",
        "tldr",
        "bat",
        "fonts-jetbrains-mono",
        "fish",
        "gnome-tweaks",
        "stow",
        "wlogout",
      ]
  tags:
    - install
    - tools
