- name: required libraries for wezterm
  become: true
  apt:
    name: ["curl", "apt-transport-https"]
  tags:
    - wezterm
    - install
- name: wezterm archive-keyring.gpg download
  shell: curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
  tags:
    - wezterm
    - install
- name: wezterm BPPA setting
  become: true
  shell: echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
  tags:
    - wezterm
    - install
- name: wezterm apt installation
  become: true
  apt:
    update_cache: yes
    name: wezterm
  tags:
    - wezterm
    - install
