#!/usr/bin/env bash

install() {
  # fzf
  if [ ! -d "$HOME"/.fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  else
    echo "fzf already installed, pulling latest change"
  fi
  cd ~/.fzf || exit
  git pull && ~/.fzf/install

  # tpm
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  # fd
  sudo apt install fd-find
  ln -s "$(which fdfind)" ~/.local/bin/fd
  # bat
  sudo apt install bat
  ln -s "$(which batcat)" ~/.local/bin/bat
  # starship
  curl -sS https://starship.rs/install.sh | sh
}

choice=3
echo "1. Install all [fzf, fd, tpm, fd, starship, rust, php]"
echo "2. Stop"
echo -n "Chose one [1, 2]: "

while [ "$choice" -eq 3 ]; do
  read -r choice
  if [ "$choice" -eq 1 ] ; then
    install
  elif [ "$choice" -eq 2 ] ; then
    exit
  else
    choice=3
    echo "Error! Choose [1 or 2]"
    echo -n "Chose one [1, 2]: "
  fi
done

