#!/usr/bin/env bash

## Install ansible
sudo apt update -y
sudo apt install -y curl git software-properties-common ansible

## Ansible playbook
# sudo ansible-playbook local.yml

## Pull ansible
# sudo ansible-pull -U https://github.com/MoXcz/ansible.git
