import = [ "~/.config/alacritty/themes/everforest_dark.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.6

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13
